import React from "react";

export default function TermsAndConditionPage() {
  return (
    <main className="bg-[#efefef] py-24">
      <div className="max-w-[1300px] mx-auto px-5 md:px-[60px] text-[#74405b]">

        {/* GENERAL TERMS */}
        <h2 className="text-[14px] font-bold underline mb-6 uppercase">
          GENERAL TERMS
        </h2>

        <ul className="text-[14px] font-medium space-y-0 list-disc pl-6 mb-10">
          <li>Entry in Locations Hub premises would be permitted only after sharing the booking details generated by the website.</li>
          <li>Since our studio is out of the city and we recommend to get your private vehicle, while returning you may not be able to avail cabs/ola/uber services.</li>
          <li>We provide complimentary WiFi services to all our guests.</li>
          <li>All the payments at the studio needs to be in Cash/Card or UPI. We don’t accept cheque payments.</li>
          <li>Maximum crew allowed for Pre Wedding | Maternity are 10.</li>
          <li>Maximum crew allowed for Product | Garment | Fashion are 20.</li>
          <li>Booking done at Locations Hub is on a sharing basis.</li>
          <li>Client must ensure that his own public liability insurance is operative for all persons coming in the studio during the hours of use.</li>
          <li>One single make-up room is provided for the entire team.</li>
          <li>Smoking is permitted in designated smoking area only.</li>
        </ul>

        {/* BOOKING & PAYMENT TERMS */}
        <h2 className="text-[14px] font-bold underline mb-6 uppercase">
          BOOKING & PAYMENT TERMS
        </h2>

        <ul className="text-[14px] font-medium space-y-0 list-disc pl-6 mb-10">
          <li>All packages displayed on the website are excluding GST.</li>
          <li>We accept bookings only through our website.</li>
          <li>Booking amount is non-refundable.</li>
          <li>Balance amount is to be paid before the shoot starts.</li>
          <li>Security deposit is mandatory.</li>
          <li>Booking can be rescheduled, if you inform us 48 hours prior to your shoot.</li>
          <li>All the people accompanying you will be accounted for.</li>
        </ul>

        {/* HIRE TERMS FOR STUDIO AND EQUIPMENTS */}
        <h2 className="text-[14px] font-bold underline mb-6 uppercase">
          HIRE TERMS FOR STUDIO AND EQUIPMENTS
        </h2>

        <ul className="text-[14px] font-medium space-y-0 list-disc pl-6 mb-10">
          <li>In case there is another client waiting for using the same set, you can use it for maximum 30 mins at a stretch.</li>
          <li>All the equipments/props belong to Locations Hub.</li>
          <li>Client cannot modify or alter the placement of equipment/props in any way.</li>
          <li>Client cannot use the equipment/props in a manner not recommended by the manufacturer.</li>
          <li>Equipment/props must be returned promptly after use.</li>
          <li>No decorations, alterations or additions to the studio are allowed without written consent.</li>
          <li>One couple per booking is allowed to shoot.</li>
        </ul>

        {/* RESTAURANT AND ACCOMMODATION */}
        <h2 className="text-[14px] font-bold underline mb-6 uppercase">
          RESTAURANT AND ACCOMMODATION
        </h2>

        <ul className="text-[14px] font-medium space-y-2 list-disc pl-6 mb-10">
          <li>Room service is available till 10 pm.</li>
          <li>Early check in and late checkout request will be entertained subject to availability.</li>
          <li>Restaurant is functional between 8am to 10pm.</li>
          <li>Outside F&B are strictly not allowed.</li>
          <li>Late check outs will be charged additional as per package.</li>
        </ul>

        {/* BREAKAGES, LOSSES AND DAMAGES */}
        <h2 className="text-[14px] font-bold underline mb-6 uppercase">
          BREAKAGES, LOSSES AND DAMAGES
        </h2>

        <ul className="text-[14px] font-medium space-y-0 list-disc pl-6 mb-10">
          <li>Locations Hub will not be liable for any loss, theft or damage of any personal equipment or valuables.</li>
          <li>Any breakages, losses or damages caused to the studio or equipment by client or team shall be liable to pay.</li>
          <li>All equipment and services are supplied at the risk of the client.</li>
          <li>Your personal belongings are your responsibility.</li>
        </ul>

        {/* MEDIA USAGE RIGHTS */}
        <h2 className="text-[14px] font-bold underline mb-6 uppercase">
          MEDIA USAGE RIGHTS
        </h2>

        <ul className="text-[14px] font-medium space-y-3 list-disc pl-6">
          <li>
            By renting our location, you acknowledge and agree that we retain the right to use any photo or video content captured on our premises for non-commercial purposes, including posting on our social media platforms.
          </li>
        </ul>

      </div>
    </main>
  );
}